[package]
name = "bevy-testing-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
naia-shared = { version = "0.13.1" }
bevy_ecs = { version = "0.8", default-features=false}